all:
  hosts: # /etc/hosts 파일에 등록한 각 노드의 호스트명 
    ubun22001:
      ansible_host: ubun22001
    ubun22002:
      ansible_host: ubun22002
    ubun22003:
      ansible_host: ubun22003
  children:
    kube_control_plane: # apiserver, controller-manager, schedular, etch 실행 
      hosts:
        ubun22001:
        ubun22002:
        ubun22003:
    kube_node: # 워커노드 리스트 
      hosts:
        ubun22001:
        ubun22002:
        ubun22003:
    etcd: # Key-Value 형태의 클러스터 정보 보관 
      hosts:
        ubun22001:
        ubun22002:
        ubun22003:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
